### ISSUE TITLE
Migrate project to work as an action

### ISSUE THREAD

**Issue by Bullrich** [paritytech/github-issue-sync#43]
## Why?
The idea of this change is to provide 3 improvements:
- Remove the need of a server.
- Greatly improve Developer Experience (DX) so anyone can use it.
- Rewrite the app to have a more consistent codebase.
### Remove the need of a server
Rewriting the GitHub app into an action would allow us to execute it as a single execution function, removing the need to have a running instance of this app in a server.
### Greatly improve DX
Currently, when someone decides to modify anything with the app, they must contact an API endpoint with a credential. This implementation is difficult which ends up requiring the OpsTooling to do it ourselves. So, when implementing this system we are the ones who need to install it. By converting it into an action other users can use this app without the need to have us intervene.
### Rewrite the app to have a more consistent codebase
The app has several entry points and connections, this document proposes a simplification of it. More info available in the architecture section.
### Entrypoint
The action's entrypoint will be set up by two kind of events:
```yml
on:
  issues:
    # updates when a issue is modified
    types:
      - opened
      - reopened
      - labeled
      - transferred
  # this can be manually triggered by going to the action's tab in the repository
  workflow_dispatch:
    inputs:
      syncIssues:
        description: 'Sync all issues available in the repository'
        required: true 
        type: boolean 
```
It will sync with two types of events, automatically, when a issue is modified, or manually, when the workflow is manually triggered by going to the action tab.
### Configuration
At the time of configurating rules we can set everything in the action file.
```yml
with:
  # Token with the following permissions: write:projects. 
  token: ${{ secrets.PROJECTS_TOKEN }}
  # The number of the project which the issues will be synced to
  project: 123
  # The name of the project field which the issue will be assigned to
  target-project-field: Team
  # The value which will be set in the field, in this case the team's name
  target-project-field-value: Foo
  # Optional field, only execute on issues with a given label
  label:
    - ops
    - ci
    - leads
```
For the token we would require one that has access only to project, allowing us to link the issue to a particular project. Some experimentation is required in this area to find the ideal permission access but it should be easy to do.
The token could be added either as per repository or a global one for [the organization](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-organization).
### Flow
The flow would be quite straightforward, if the action is initialized over a `workflow_dispatch`, it will fetch all the issues from the project and iterate over them assigning them the correct condition. 
But, if it's initialized through a Issue event, it will check which condition triggered the action and will act accordingly. You can visualize the flow in the following diagram:
```mermaid
flowchart LR
Start-up --> SyncOrIssue{Is it a\nworkflow dispatch?}
SyncOrIssue --> |Yes|Fetch[(Fetch all\nissues ID)]
Fetch --> Assign[[Assign Issue\nto Project Ids]]
SyncOrIssue --> |No|Switch((Switch over\nthe issue state))
Switch --> opened --> Assign
Switch --> transfered --> Assign
Switch --> labeled --> Label[[Calculate condition]] --> Assign
Switch --> closed --> ChangeState[[Change Issue\nState in Project]]
subgraph issue-event
opened
transfered
labeled
closed
end
```
### Architecture 
The architecture will be defined in an entry point (the core) and will initialize all the required values, sending everything to a business layer that will be the one in charge of executing the side effect.
```mermaid
flowchart LR
A(Event) --> |Action is initialized| Core(Core)
Core(Core) --> |Initialized GitHub app| Business(Business layer)
Business --> Logger(Logger)
Business --> Octokit(Octokit)
    subgraph Application
        Business
        Logger
        Octokit
    end
```
The core will parse all the configuration coming from both the event and the action workflow file and parse it into an agnostic object:
```typescript
// Example of the event data
interface IEventData {
	issueId?: number;
	event: "opened issue" | "closed issue" | "labeled issue" | "transfered issue" | "sync all issues"
	issueState?: "open" | "closed"
	config: {
		project: number,
		targetField: string,
		targetValue: string
	}
}
```
Everything related to interacting with GitHub (modifying the state, fetching configurations, etc) will be encapsulated in an wrapper that will be accessed by the business layer:
```typescript
interface IGitHub {
	assignProjectToIssue(issueId: number, projectId: number): Promise<boolean>;
	getIssueState(issueId: number): Promise<"open" | "closed">;
	getAllIssuesId(): Promise<number[]>;
	getProjectIdFromIssue(issueId: number): Promise<number>;
	changeIssueStateInProject(issueId: number, state: "todo" | "in progress" | "blocked" | "done");
}
```
Everything related to interacting with the logging system will also be wrapped in its own wrapper:
```typescript
interface ILogger {
	log(message: string): void;
	warn(message: string): void;
	error(message: string | Error): void;
}
```
This would allow us to have an agnostic business logic where we can write a clean and easy to understand logic.
```typescript
const octokit: IGitHub;
const logger: ILogger;
/** Overly simplified example of how it would work **/
async function execute(eventData: IEventData) {
    const { issueId, event } = eventData;
    if (event === "opened issue") {
        await octokit.assignProjectToIssue(eventData.issueId, eventData.config.project);
        logger.log(`Assigned issue #${issueId} to project ${eventData.config.project}!`);
    } else if (event === "closed issue") {
        if (await octokit.getProjectIdFromIssue(issueId) > 0) {
            await octokit.changeIssueStateInProject(issueId, "done");
            logger.log(`Updated issue #${issueId} to done!`);
        }
    } else if (event === "sync all issues") {
        const issues = await octokit.getAllIssuesId();
        for (let i = 0; i < issues.length; i++) {
            await octokit.assignProjectToIssue(issues[i], eventData.config.project);
            logger.log(`Assigned issue #${issues[i]} to project ${eventData.config.project}!`);
        }
    }
}
```

This would also **allow us to test the logic by substituting the dependencies**. And if, for whatever reason, we want to port this code to be a GitHub app or to run in GitLab, *the abstraction would make it quite straightforward*.
## Multiple project configuration
By setting up multiple executions, the action can be executed multiple times for different projects, allowing some better level of customization.
```yml
on:
  issues:
    # updates when a issue is modified
    types:
    - opened
    - reopened
    - labeled
    - transferred
  # this can be manually triggered by going to the action's tab in the repository
  workflow_dispatch:
    inputs:
      syncIssues:
        description: 'Sync all issues available in the repository'
        required: true 
        type: boolean 
jobs:
  lead-board:
    runs-on: ubuntu
    steps:
      - uses: paritytech/github-issue-sync
        with:
          token: ${{ secrets.PROJECTS_TOKEN }}
          project: 123
          label:
          - leads
  dev-board:
    runs-on: ubuntu
    steps:
      - uses: paritytech/github-issue-sync
        with:
          token: ${{ secrets.PROJECTS_TOKEN }}
          project: 321
          target-project-field: Team
          target-project-field-value: Foo
          label:
          - engineering
          - ci
```

# Completion requirements:
- [x] Works as an action.
- [x] Has an updated readme
- [x] Has unit tests.
- [x] Has been tested in some system.
